# Generated by Django 3.1.4 on 2020-12-08 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'CaseLocation',
                'verbose_name_plural': 'CaseLocations',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cod_dane', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cod_dane', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Deparments',
                'ordering': ('cod_dane',),
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Gender',
                'verbose_name_plural': 'Genders',
            },
        ),
        migrations.CreateModel(
            name='Possitive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_report', models.DateField()),
                ('notification_date', models.DateField()),
                ('age', models.IntegerField()),
                ('symptoms_date', models.DateField(null=True)),
                ('case_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='possitives', to='covid_co_api.caselocation')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='possitives', to='covid_co_api.city')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='possitives', to='covid_co_api.gender')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Possitives_reported', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Possitive',
                'verbose_name_plural': 'Possitives',
                'ordering': ('notification_date',),
            },
        ),
        migrations.CreateModel(
            name='SeverityStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'SeverityStatus',
                'verbose_name_plural': 'SeverityStatus',
            },
        ),
        migrations.CreateModel(
            name='RecoveryDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recovery_date', models.DateField()),
                ('possitive', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='possitive_recovery', to='covid_co_api.possitive')),
            ],
            options={
                'verbose_name': 'RecoveryDate',
                'verbose_name_plural': 'RecoveryDates',
            },
        ),
        migrations.AddField(
            model_name='possitive',
            name='severity_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='possitives', to='covid_co_api.severitystatus'),
        ),
        migrations.CreateModel(
            name='DeathDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('death_date', models.DateField()),
                ('possitive', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='possitive_deaths', to='covid_co_api.possitive')),
            ],
            options={
                'verbose_name': 'DeathDate',
                'verbose_name_plural': 'DeathDates',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='covid_co_api.department'),
        ),
    ]
